use std::collections::HashMap;

use super::{depot::Depot, nurse::Nurse, patient::Patient};
use serde::{Serialize, Deserialize};

/// Represents a problem instance for the vehicle routing problem with time windows and capacity constraints.
/// 
/// This struct contains all necessary data for an instance, including metadata, depot details, patient information,
/// travel times between locations, and nurse-related parameters. The instance is used to configure and evaluate
/// solutions generated by the genetic algorithm.
///
/// # Fields
/// - `instance_name` - The name of the instance.
/// - `nbr_nurses` - The number of nurses available for this instance.
/// - `capacity_nurse` - The capacity of each nurse.
/// - `benchmark` - The benchmark objective value for the instance (e.g., an estimated minimum travel time).
/// - `depot` - Depot-related information such as return time and coordinates.
/// - `patients` - A mapping from patient identifiers to their corresponding patient data.
/// - `travel_times` - A matrix of travel times where `travel_times[i][j]` represents the travel time from patient i to patient j.
/// - `nurses` - A vector of nurses available for the instance. This field defaults to an empty vector if not provided.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Instance {
    pub instance_name: String,
    pub nbr_nurses: u32,
    pub capacity_nurse: u32,
    pub benchmark: f64,
    pub depot: Depot,
    pub patients: HashMap<String, Patient>,
    pub travel_times: Vec<Vec<f64>>,
    #[serde(default)]
    pub nurses: Vec<Nurse>,
}

impl Instance {
    /// Adds nurses to the instance based on the `nbr_nurses` field.
    /// 
    /// This method populates the `nurses` vector by creating new `Nurse` objects, each initialized
    /// with the nurse capacity specified in `capacity_nurse`. If `nbr_nurses` is greater than zero,
    /// it adds that many nurses; otherwise, no nurses are added.
    pub fn add_nurses(&mut self) {
        if self.nbr_nurses > 0 {
            for _ in 0..self.nbr_nurses {
                self.nurses.push(Nurse::new(self.capacity_nurse, 0, 0.0, 0.0));
            }
        }
    }
}
